submissionConfig:
  defaultSparkVersion: 3.1
  sparkImages:
    - version: 3.2
      type: java
      image: ghcr.io/datapunchorg/spark:spark-3.2.1-1643336295
    - version: 3.2
      type: python
      image: ghcr.io/datapunchorg/spark:pyspark-3.2.1-1643336295
    - version: 3.1
      type: java
      image: ghcr.io/datapunchorg/spark:spark-3.1-1643212945
    - version: 3.1
      type: python
      image: ghcr.io/datapunchorg/spark:pyspark-3.1-1643212945
  sparkConf:
    key1: value1
    key2: value2