apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXhOVEl5TkRRd05Gb1hEVE15TURVeE1qSXlORFF3TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHU3CmdSNVkyOEVNUFJnUWFJY2syMTZIWGZRbTJJLzhMQitWRnR4bkYyM2drT0dCWThteEJnK3BSd3VVQ2NKdUJBcWkKR0JJM0dyazU2U0h2ZHFKcjBKNHBwZWJuSVVRRURUK2ZuN293SGhaMzZYclJHR2tqZHJlNm5INm1uTXFyZ2NjOQp2dkFCeVlrN1hiRDI3VU50V0FOcHhkd0s3djJ5QUx1RzVhWVNJdUJhMXVwN0RFdGp6SmhBcUw0cXlzakhxVjZIClU1N05LdVJBMGNIL2ZWUGtiSmFuU1dTQkUrT3BSTHp0UjArdjZrMksrMThRcTVYQy9WK1p6cTEwZWsvTHdrODkKd1E5ZDFHbmQyamNINkZxSFpsQ2lxTXNqd2k2WHdBVjVXb0diV2dOenhsUXM2RDFYSmxhU21TcUsrRUhVdzhmSwo1NnBOa214T1ZOYmo4ZmpNRWs4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHaXlVL01MSlpSWFJZM1drODJLOGQycU9KV2ZNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDd1V2WmxtTGhNMmw4TDFkaXJvMVZVM0lhSjFaOWcxZDl1WjVKbktjZk5ySFlNWjdXVApwZjZqMVgwdUV0bUhNOWFNYWIrQ2p6TEcvZk9ybjJYZzJXa1RJTi9wOWdKTEV5OVo1WlFjZ0pRdFlBR3VmdUxpCnc3by9QU1piM0VLV2FqTGQrYnJFSmR2VlE0RERnRG5Kemg3WkxJalN5SzU1OUZzSG0xL2RJQXluWGlxaFhwOFEKNi9MZzlTTXZ4cFROUFhkenZwRklBQWI0cGtyQmtkbnZ3WVVhbGIra28wSEhTT0pvbDBWYnlZdXNwQmk5L1BTUApUbENqeWFGclVZZ29EQ0RnOWxqY1hrSkJSandyMW5yRHNyQmRvUFBDLy9zby9XNjNqd0VPbmF3QjBNVzlucTBoCjRCRnhHZENjUWxmNzRHRTZSRlUrTUFlaURCd3Z2MmdsRWhvNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://736166578017644C4AA70BC51277D307.gr7.us-west-1.eks.amazonaws.com
  name: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
contexts:
- context:
    cluster: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
    user: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
  name: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
current-context: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-1:133628591400:cluster/my-eks-01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - my-eks-01
      command: aws

