name: Manually release Spark Operator docker image

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the Docker image for Spark History Server
        run: |
          IMAGE_TAG=operator-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}
          docker build . --file Dockerfile --tag ghcr.io/datapunchorg/spark-on-k8s-operator:${IMAGE_TAG}
          docker images
          docker build -t ghcr.io/datapunchorg/spark-on-k8s-operator:spark-history-server-3.2-${{github.ref_name}}
          docker push ghcr.io/datapunchorg/spark-on-k8s-operator:spark-history-server-3.2-${{github.ref_name}}
